### PR TITLE
Lets use the switch(argument) cycle

### PR DESCRIPTION
**Pull request by montlikadani**
- Empty string is not ignoring cases

### CODE REVIEW

**Review by smessie — CHANGES_REQUESTED** [review]
The Java compiler will internally replace a switch statement which takes a String to multiple if else conditions, so this change is not needed.
What advantage does the #equals have over #equalsIgnoreCase?
Which changes have effect on the 'empty string is not ignoring case'?
Could you clarify those topics before merging?
Thanks for doing a pull request!

**Comment by montlikadani** [comment]
Unlike `if-then` and `if-then-else` statements, the switch statement can have a number of possible execution paths. (https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html)

`equalsIgnoreCase()` methods ignores the case during comparison. For e.g. The `equals()` method would return false if we compare the strings “TEXT” and “text” however `equalsIgnoreCase()` would return true.

**Comment by smessie** [comment]
I'm okay with the change to Switch now.
But for the `equals`, isn't that what we want?

**Comment by montlikadani** [comment]
It is not necessary to check the large letters for an empty string.

**Comment by smessie** [comment]
Ah right, thanks

**Comment by FKD13** [comment]
I would do this with a Hashmap,
for quicker lookups and better code style.

**Comment by smessie** [comment]
Correct, implemented this in 4a524494bf84953369f5f7ba9347ef02655b029d.

**Pull request merged**
